spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
      # 主数据源
      db-main:
        url: jdbc:p6spy:mysql://localhost:3306/main?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
        username: root
        password: password
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      # 副数据源
      db-sso:
        url: jdbc:p6spy:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
        username: root
        password: password
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      # 从数据源
      db-slave:
        url: jdbc:p6spy:mysql://localhost:3306/slave?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
        username: root
        password: password
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
